name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out âœ”
      uses: actions/checkout@v3
    - name: Setup .NET ğŸ”¨
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies ğŸ–¥
      run: dotnet restore
    - name: Build ğŸ—
      run: dotnet build --no-restore
    - name: Test ğŸ› 
      run: dotnet test --no-build --verbosity normal
          